# Generated by Django 5.2.3 on 2025-06-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="period",
            field=models.CharField(
                choices=[
                    ("none", "Не повторять"),
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                ],
                default="none",
                max_length=10,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("started", "Запущена"), ("done", "Завершена")],
                default="Создана",
                max_length=20,
                verbose_name="Статус сообщения",
            ),
        ),
    ]
