# Generated by Django 5.2.3 on 2025-06-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_mailing_period_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("ok", "Успешно"), ("fail", "Ошибка")], max_length=20, verbose_name="Статус рассылки"
            ),
        ),
    ]
