# Generated by Django 5.2.3 on 2025-06-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailingattempt_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "permissions": [("view_all_clients", "Может просматривать всех клиентов")],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("view_all_mailings", "Может просматривать все рассылки"),
                    ("deactivate_mailing", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("view_all_messages", "Может просматривать все сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
